# Generated by Django 5.2.12 on 2026-08-14 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_device_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.student'),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student',), name='one_active_device_per_student'),
        ),
    ]
