# Generated by Django 5.2.12 on 2026-08-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_device_student_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('device_fingerprint',), name='one_active_device_fingerprint'),
        ),
    ]
