# Generated by Django 5.2.12 on 2026-08-22 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_device_one_active_device_fingerprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('enrolled', 'Enrolled (first device)'), ('re_enrolled', 'Re-enrolled (same physical device)'), ('deactivated', 'Deactivated by admin'), ('reactivated', 'Reactivated by admin'), ('mismatch_student_has_device', 'Blocked: student already has a different active device'), ('mismatch_fingerprint_taken', 'Blocked: this device fingerprint already belongs to another student')], max_length=40)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conflicting_student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_conflicts_against', to='users.student')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='users.device')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_events', to='users.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
