# Generated by Django 5.2.12 on 2026-03-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='stopped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
