# Generated by Django 5.2.12 on 2026-03-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_session_is_submitted_session_stopped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='previous_qr_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
