# Generated by Django 5.2.12 on 2026-03-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_session_previous_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='original_status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('manual', 'Manual Override')], default='present', max_length=10),
        ),
    ]
