# Generated by Django 5.2.12 on 2026-04-02 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_qrscan'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRTokenHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token', models.CharField(max_length=255)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.session')),
            ],
            options={
                'unique_together': {('session', 'qr_token')},
            },
        ),
        migrations.DeleteModel(
            name='QRScan',
        ),
    ]
