# Generated by Django 5.2.12 on 2026-08-12 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_qrtokenhistory_delete_qrscan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='previous_qr_token',
        ),
    ]
