# Generated by Django 5.2.12 on 2026-08-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_session_previous_qr_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='expected_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='present_count',
            field=models.IntegerField(default=0),
        ),
    ]
