# Generated by Django 5.2.12 on 2026-08-19 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_session_expected_count_session_present_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRTokenHistory',
        ),
    ]
