# Generated by Django 5.2.12 on 2026-08-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_delete_qrtokenhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='previous_qr_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='previous_qr_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
